name: Android CI

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

env:
  REPO: ${{ github.event.repository.name }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SECRET }}
  SONAR_HOST_URL: "https://sonarqube.trustly.one"
  SONAR_PROJECT_KEY: "trustly-android"

jobs:
  android_tests_sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Clean Build
        run: |
          cd trustly-android-sdk || exit
          ./gradlew clean build --warning-mode all

      - name: Run createDebugUnitTestCoverageReport
        run: |
          cd trustly-android-sdk || exit
          ./gradlew createDebugUnitTestCoverageReport

      - name: Install SonarQube Scanner
        run: |
          SONAR_SCANNER_VERSION=5.0.1.3006
          SONAR_SCANNER_DIR=/opt/sonar-scanner

          curl -o sonar-scanner-cli.zip -L "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}-linux.zip"

          sudo apt-get install -y unzip
          unzip sonar-scanner-cli.zip
          sudo mv sonar-scanner-${SONAR_SCANNER_VERSION}-linux ${SONAR_SCANNER_DIR}

          echo "${SONAR_SCANNER_DIR}/bin" >> $GITHUB_PATH
          echo "SonarScanner installed successfully!"

      - name: Verify SonarQube Scanner Installation
        run: sonar-scanner --version

      - name: Run SonarQube Scanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN} \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }} \
            -Dsonar.scm.revision=$(git rev-parse HEAD) \
            -Dsonar.coverage.jacoco.xmlReportPaths=/home/runner/work/trustly-android/trustly-android-sdk/build/reports/coverage/test/debug/report.xml \
            -Dsonar.sources=/home/runner/work/trustly-android/trustly-android/trustly-android-sdk/src \
            -Dsonar.java.binaries=/home/runner/work/trustly-android/trustly-android/trustly-android-sdk \
            -Dsonar.java.libraries=/home/runner/work/trustly-android/trustly-android/trustly-android-sdk \
            -Dsonar.coverage.exclusions=**/test/** \
            -Dsonar.scm.disabled=true